import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = Metadata{
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  const { children } = props;
  return (
    React.createElement('html', { lang: 'en' },
      React.createElement('body', { className: inter.className }, children)
    )
  );
}
